server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myunghoonju/my-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh