server:
  port: 8888

spring:
  profiles:
    include: dev
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: local_rdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
            sql: select prob_key, prob_val from properties where application=? and profile=? and label=?
        #when it's false then return 404 response if unknown server configuration data requested
        accept-empty: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
