token:
  expire: 86400000
  secret: my_over_forty_length_of_letters_for_secret_message

gateway:
  ip: 192.168.56.1

spring:
    datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
